### ISSUE TITLE
Issues list before v2 code freeze

### ISSUE THREAD

**Issue by jackjia-ibm** [zowe/zowe-install-packaging#2759]
Hi team, the PI planning meeting overlapped with System squad scrum so we didn’t get chance to sync on the progress. I’m trying to understand what issues are left before code freeze. Here are a list of issues I’m aware of.

# related to automated tests
- [ ] 1. https://github.com/zowe/api-layer/issues/2203
- [x] 2. I see a test failure related to /gateway/api/v1/greeting. I’m still investigating this.
- [x] 3. ZWESECUR job failed on ACF2, we may have a syntax error somewhere in JCL. Will need some helps who understand ACF2 better.

# other issues
- [x] 4. sometimes in Zowe job log, app-server logs shown as bad encoding
- [x] 5. related to ZSS returning 401 error https://openmainframeproject.slack.com/archives/CC5UUL005/p1648564102517869
- [ ] 6. install app-server plugins in containerization build. are PR#2747 and PR#2758 trying to resolve the issue?
- [x] 7. where are we with config manager integration?

# unfinished PRs
- [x] 8. PR#2678 https://github.com/zowe/zowe-install-packaging/pull/2678 -- Do you want me to make the changes and merge the PR?
- [ ] 9. PR#2757 https://github.com/zowe/zowe-install-packaging/pull/2757 -- is this required for GA?

Thanks for any updates and please refer to the issue item number here. Also if there are more issues I’m not aware of, please feel free to share and I will add to the list.

**Comment by jackjia-ibm** [comment]
item #2 fixed, should test `/api/v1/greeting` instead of `/gateway/api/v1/greeting`

**Comment by jackjia-ibm** [comment]
Updates on completion based on slack messages:

[Carson Cook](https://app.slack.com/team/U017QBMAXLY)  [16 hours ago](https://openmainframeproject.slack.com/archives/CH9R3FD1V/p1649368842311889?thread_ts=1649365138.826659&cid=CH9R3FD1V)
#5 is solved, had a bad config with gateway internal connector enabled but ssl not configured correctly

[Sean Grady](https://app.slack.com/team/UC5K5HWKD)  [11 hours ago](https://openmainframeproject.slack.com/archives/CH9R3FD1V/p1649386380499569?thread_ts=1649365138.826659&cid=CH9R3FD1V)
#4 is fixed. app-server log is fixed, strange solution but unrelated to the zwe help encoding issue, which i hope is fixed but not sure?

**Comment by jackjia-ibm** [comment]
[Jack T. Jia](https://app.slack.com/team/UC59FQWSC)  [< 1 minute ago](https://openmainframeproject.slack.com/archives/CH9R3FD1V/p1649442135166609?thread_ts=1649365138.826659&cid=CH9R3FD1V)
I made small change on PR#2678 to define error code. test looks ok and now it’s merged.

**Comment by jackjia-ibm** [comment]
For item 7, this will not be included in April GA. So consider this is not blocking issue for GA.

[Sean Grady](https://app.slack.com/team/UC5K5HWKD)  [20 hours ago](https://openmainframeproject.slack.com/archives/CH9R3FD1V/p1649386270328369?thread_ts=1649365138.826659&cid=CH9R3FD1V)
joe and i are doing a test of config manager integration for zss before rolling it out for use overall. i aim to begin on the second phase integration into install-packaging next week because right now i'm doing doc work (edited)

**Comment by jackjia-ibm** [comment]
For item 3, Mark found it's caused by the HLQ definition. The HLQ must be real HLQ and if it has multiple qualifiers, the job will fail.

Add `--ignore-security-failures` option to `zwe init security` so pipeline can ignore error and move on.
