### ISSUE TITLE
Version 3 Systems Squad

### ISSUE THREAD

**Issue by balhar-jakub** [zowe/zowe-install-packaging#3482]
Epic for the squad to link all the relevant work that the squad intend to prepare for the V3 release so we can track how far we are. 
```[tasklist]
### Tasks
```

**Comment by MarkAckert** [comment]
Collecting checklists for producing v3 zowe. Will discuss with squad and decide if we need to split it into issues or work on it from here.

- [x] Get Zowe v3 FMID and PTF numbers - @ojcelis 
- [x] Check zowe-actions and determine if we need to branch for v3
  * [ ] zowe-actions zlux-actions will be branched by zlux team, rest won't. 
- [x] Branch zowe-dependency-scan-pipeline repo *[not required]*
- [ ] Branch zowe-install-packaging-tools for v3
- [x] Branch zowe-install-packaging. v2.x/staging -> v3.x/staging. v2.x/rc -> v3.rx/rc. v2.x/master -> v3.x/master
- [x] Update manifest and other hard-coded 'v2' references in zowe-install-packaging (NOT dependency versions)
      * Include AZWE002 -> AZWE003 updates
- [ ] Update `zowe-release` repo for v3. (Copy v2 actions -> v3)
- [ ] Produce v3.0.0-SNAPSHOT. At this point, it's functionally the same as v2.x and should work, however, it is a new FMID.
- [ ] Producer 3.0.0-RC1 from v3.x/rc . Check binaries match expectations (AZWE003, no PTFs).
- [ ] Once RC1 looks good, delete it. We will re-create it for actual release.
- [ ] Update dependencies in manifest.json component by component and test per usual nightly / PR methods
- [ ] Update Zowe.github.io with a v3 section

While the above is happening, component squads will likely follow a similar branch, release, and artifact validation pathway. Once they've completed validating their component artifacts then we can bring them into manifest.json.

**Comment by 1000TurquoisePogs** [comment]
I don't see anything incomplete here, I'm going to close this as done.
