### ISSUE TITLE
Pax build: Separate out install and config

### ISSUE THREAD

**Issue by Joe-Winchester** [zowe/zowe-install-packaging#418]
**As a** Zowe SMP/E installer,  
**I want** to separate out the install and configure stages
**so that** I can do an install first, then config from the installed directory.

*Details/notes*
#433 will do a more complete job of allowing the user to specify config at launch time to in order run multiple servers from the same runtime directory, but this item is just about separating out a single install/config cycle.

#### MVP
- [x] Create a new zowe-configure.sh script that orchestrates the configuration and remove all the config from the current zowe-install.sh. Call zowe-configure.sh at the end of zowe-install.sh #539
- [x] Move all of the config scripts into a new config directory. During install copy the config scripts (+ yaml) into the install target directory under /scripts/config (or similar) #540
- [x] Provide a zowe-install -I option that doesn't run the zowe-configure.sh at the end.
- [x] ensure documentation is updated for these steps #530 
- [x] Ensure there are no regressions in functionality - that all enhancements/bug fixes in staging are part of this build #462

#### Nice to have
- [ ] Create JCL to set up security config #518
- [x] Create SAMPLIB entries for the PROCLIB/PARMLIB in the install #519

#### Acceptance Criteria

*Given* an unpaxed zowe 'convenience build' and a configured yaml
    *When* I run zowe-install.sh 
    *Then* It installs and configures Zowe as today and the result is startable.

*Given* an unpaxed zowe 'convenience build'
    *When* I run zowe-install.sh -I
    *Then* It installs zowe in an unconfigured state and the configure scripts and yaml are availabe in the installed target directory

*Given* an unconfigured, but installed zowe build with a configured yaml
    *When* I run <zowe_root_dir>/scripts/configure/zowe-configure.sh
    *Then* The zowe config is installed and the result is startable.

Ensure that all documentation is up to date.

**Comment by 1000TurquoisePogs** [comment]
Seems to no longer be relevant and basically accomplished in v2
